### ISSUE TITLE
Please add my site

### ISSUE THREAD

**Issue by durraniu** [jhelvy/distillery#11]
Thanks for collecting distill sites in one place. Please add mine. Here are the details:  

Site Name: Umair Durrani  
Site URL: https://udurrani.netlify.app/
Source URL: https://github.com/durraniu/udurrani_distill

**Comment by jhelvy** [comment]
Welcome!

**Comment by durraniu** [comment]
Thanks! Just one thing: the source link is also directed to the site url.

**Comment by jhelvy** [comment]
Oops - good catch! That's a bug for all of the links, fixing it now!
