### ISSUE TITLE
Add MFEO post (distill + postcards)

### ISSUE THREAD

**Issue by apreshill** [jhelvy/distillery#21]
Hi @jhelvy - I updated the post here:

https://github.com/rbind/apreshill/tree/master/content/post/2020-12-22-postcards-distill

https://alison.rbind.io/post/2020-12-22-postcards-distill/

You are welcome to add it here! I'm not sure the process, but it cannot be imported due to the fact that it is embedded in a website (instead of a standalone article).

Thanks :)

**Comment by jhelvy** [comment]
Awesome! I'll add it tonight. My plan is to copy over the source files and then edit the yaml to build it as a distill article, plus add an attribution statement at the top linking back to the original article.

**Comment by jhelvy** [comment]
It's [up](https://jhelvy.github.io/distillery/tips_and_tricks.html)!
