### ISSUE TITLE
Monthly auto re-render failing

### ISSUE THREAD

**Issue by jhelvy** [jhelvy/distillery#45]
@etiennebacher, looks like the monthly deploy failed. It seems it just gets stuck on taking the screenshots for some reason. Here's what the build log says: 

```
https://alexkgold.space/ screenshot completed
https://lab.abj.org.br/ screenshot completed
https://oliviergimenez.github.io/bayesian-stats-with-R/ screenshot completed
https://beatrizmilz.com/ screenshot completed
https://milesmcbain.xyz/ screenshot completed
https://datascidani.com/ screenshot completed
https://emitanaka.org/ screenshot completed
https://www.ericekholm.com/ screenshot completed
https://www.etiennebacher.com/ screenshot completed
https://hfshr.xyz screenshot completed
https://ijeamaka-anyene.netlify.app/ screenshot completed
https://jmbuhr.de screenshot completed
https://jeffreyasselin.netlify.app/ screenshot completed
Attempting to interrupt gracefully; press Esc/Ctrl+C to force interrupt


Execution halted
Error: The operation was canceled.
```  

It stayed on that task for 6 hours again before it quit. I don't think anything is wrong with the site or the workflow, just that the screenshot process freezes mid-way. 

Perhaps there is a way to add an internal timer where if the screenshot isn't taken after maybe 60 seconds it skips that site and moves on?

**Comment by jhelvy** [comment]
Just noticed that the cron job ran again, but something went wrong. It didn't deploy properly to the gh-pages branch. I'm re-running an older job to fix it. I'm also wondering how necessary it is to have the cron job. We'll probably keep updating the site over time, and if someone's screen shot is outdated they can always post an issue and we can update it.

**Comment by etiennebacher** [comment]
Hi, sorry I come back a bit late to this. Indeed if this repo is frequently updated, this cron job is not necessary. It's your repo so remove the action if you want ;)

**Comment by jhelvy** [comment]
I think I'll remove it. It's been hard to test it to make sure it's working, and on the last run it pushed only a couple files to the `gh-pages` repo which killed the site. Thanks for putting it together though - I definitely learned from it (I didn't even know you could do a cron job on GA!)
