### ISSUE TITLE
add "Deploy previews with Netlifly" to tips & tricks

### ISSUE THREAD

**Issue by shannonpileggi** [jhelvy/distillery#47]
Hi John! Can we add this post to tips & tricks?

Post:
https://www.pipinghotdata.com/posts/2021-04-01-deploy-previews-with-netlifly/

Source:
https://github.com/shannonpileggi/pipinghotdata_distill/tree/master/_posts/2021-04-01-deploy-previews-with-netlifly

Thank you!

**Comment by jhelvy** [comment]
It's up!
http://distillery.rbind.io/posts/2021-04-01-deploy-previews-with-netlifly/
