### ISSUE TITLE
Add "Personalize the Distill Template" to Tips & Tricks?

### ISSUE THREAD

**Issue by ekholme** [jhelvy/distillery#49]
Hi John,

Thanks so much for putting this site together -- it's really great!

Could you add this post to the tips & tricks section?

Post:
https://www.ericekholm.com/posts/2021-04-02-personalizing-the-distill-template/

Source:
https://github.com/ekholme/ee-website/tree/master/_posts/2021-04-02-personalizing-the-distill-template

Thank you!

Eric

**Comment by jhelvy** [comment]
It's up!
https://distillery.rbind.io/posts/2021-04-02-personalizing-the-distill-template/

**Comment by ekholme** [comment]
Thanks!
