### ISSUE TITLE
Add syntax highlighting blog posts

### ISSUE THREAD

**Issue by EllaKaye** [jhelvy/distillery#57]
Hi John,

Thanks for inviting me to contribute my syntax highlighting blog posts to the distillery! Here are the details

### Part 1
Post: https://ellakaye.rbind.io/posts/2021-05-25-custom-syntax-highlighting-for-distill-part-1-modifying-the-default-theme/
Source: https://github.com/EllaKaye/ellakaye-distill/tree/main/_posts/2021-05-25-custom-syntax-highlighting-for-distill-part-1-modifying-the-default-theme

### Part 2
Post: https://ellakaye.rbind.io/posts/2021-05-26-custom-syntax-highlighting-for-distill-part-2-creating-the-palette/
Source: https://github.com/EllaKaye/ellakaye-distill/tree/main/_posts/2021-05-26-custom-syntax-highlighting-for-distill-part-2-creating-the-palette

Hopefully I've set the directory/posts up in such a way that my syntax highlighting scheme still applies, even when built on the distillery.

**Comment by jhelvy** [comment]
Great! I'll build the posts and check if the highlighting is correct before committing it.

**Comment by jhelvy** [comment]
Okay posts are up!
