### ISSUE TITLE
Empty Tips & Tricks page

### ISSUE THREAD

**Issue by spcanelon** [jhelvy/distillery#67]
Hi @jhelvy! I came to the Distillery to see if I could find any resources that might help with Oscar Baruffa's [distill yaml question](https://twitter.com/OscarBaruffa/status/1440518432399581185) but the [Tips & Tricks page](https://jhelvy.github.io/distillery/tips_and_tricks.html) didn't load

**Comment by jhelvy** [comment]
Yeah there appears to be a [bug](https://github.com/rstudio/distill/issues/403) in the latest version of {distill} where if you have more than 5 posts the blog page won't properly render. I've been hand-editing the page for the meantime following the suggested solution by @lgnbhl. But looks like the page got overwritten again by the GH Action I have set up. I'll edit and fix it again.

**Comment by jhelvy** [comment]
It's up again now: https://distillery.rbind.io/tips_and_tricks.html

You have to click on "More articles" to see more, and the thumbnails still aren't working.

**Comment by jhelvy** [comment]
This is now [fixed](https://github.com/rstudio/distill/issues/403) thanks to @cderv!
