### ISSUE TITLE
Tips and tricks blog - attaching disqus

### ISSUE THREAD

**Issue by Lextuga007** [jhelvy/distillery#68]
This might be useful for tips and tricks blogs: https://lextuga007.github.io/PhilosopherAnalyst/posts/2021-01-31-adding-disqus-to-distill-blogs/ I published this under my blog name of Philosopher Analyst but I'm happy for my name to be referenced - Zoë Turner, thanks.

**Comment by jhelvy** [comment]
Thanks! I'll try and add this.

**Comment by jhelvy** [comment]
Just added the post!

**Comment by Lextuga007** [comment]
Many thanks 😃
