### ISSUE TITLE
Add "Features" filter at the top of showcase?

### ISSUE THREAD

**Issue by jhelvy** [jhelvy/distillery#7]
Not sure how to do this, but it would be great to have a set of "features" that each site in the showcase has (e.g. "Blog", "Dark / Light Mode", etc.), and the user could filter sites based on these features. That way if they're looking for a specific feature to add to their site, they could more easily identify example sites that have those features.

**Comment by shannonpileggi** [comment]
That is a great idea! I haven't looked at how you built things yet 🧐, but I could see this looking like tags for key words. Users could select from pre-set tags or have the option to submit a new one. Users may also want to update their tags over time as they add new features.  

Another option would be to have a second kind of showcase that is highlights specific sites for specific features. Like, looking for a site that has dark mode? Go here. Or one with post card? Check this one out.

**Comment by jhelvy** [comment]
I was inspired by Alison's [project page](https://alison.rbind.io/projects/) where you can filter the project by tag. I was thinking of something like that where the showcases get filtered by clicking on a list of tags at the top. 

I think this could be done with some css tags, something like [this](https://www.w3schools.com/howto/howto_js_filter_elements.asp) maybe. It shouldn't be too hard to integrate into how I've built the showcase page. The page is built by creating a Rmd chunk for each site in the `sites.csv` file. I wrote a function that builds the chunks (see `make_rmd_chunks()` and `make_showcase_chunk()` in the [`functions.R`](https://github.com/jhelvy/distillery/blob/main/R/functions.R) file. We would just have to add the appropriate css in the `make_showcase_chunk()` function so that the tags for each site are added. Then just edit the [`theme.css`](https://github.com/jhelvy/distillery/blob/main/css/theme.css). 

I'm not sure how to come up with the tags though. One thought is to add more columns on the `sites.csv` file (one for each new tag) and use 1 / 0 to tag the sites with each feature.

**Comment by shannonpileggi** [comment]
Oooh yes!  That is very cool.

And agree with tag 1 / 0's on site.csv.

**Comment by jhelvy** [comment]
Thanks to @etiennebacher this is now up! Now all we need to do is update the sites.csv to add more categories. Anyone have ideas for how to do this? maybe crowd source this so the site owners add their own categories? Or should we just go through and add some ourselves?

**Comment by etiennebacher** [comment]
I don't think site owners will come back often on this repo, so waiting for them to categorize their sites is not a good solution in my opinion. One solution could be to make this call on twitter but that seems a bit "too much" just to put sites in categories. I think we could just do that ourselves
