### ISSUE TITLE
Distill website to add

### ISSUE THREAD

**Issue by dgkeyes** [jhelvy/distillery#70]
Howdy! Here's a new submission for you.

Site name: API Food Assets Map
URL: https://foodmap.apicouncil.org
Source code: https://github.com/rfortherestofus/api-food-asset-map

I did a bunch of custom CSS (including using TailwindCSS) to make it look a bit less like a distill site, but you can still see it in there!

**Comment by jhelvy** [comment]
Wow, nice job "hiding" the underlying distill - it's amazing what can be done with just CSS!

**Comment by dgkeyes** [comment]
Thanks! [I made a little video showing how I did it if you're interested](https://twitter.com/dgkeyes/status/1397235209913909257).

**Comment by jhelvy** [comment]
Cool! Site should rebuild and be up soon!

**Comment by dgkeyes** [comment]
Thanks!
