### ISSUE TITLE
Add post about giscus to tips and tricks

### ISSUE THREAD

**Issue by joelnitta** [jhelvy/distillery#73]
Thanks for maintaining this site, it's been a great resource while I transition to Distill!

I wrote a post about using giscus (similar to utterances, but uses GitHub Discussions instead of Issues). I hope it can be added.

Blogpost: https://www.joelnitta.com/posts/2021-11-24_using-giscus/

Source: https://github.com/joelnitta/joelnitta-home/blob/main/_posts/2021-11-24_using-giscus/index.Rmd

**Comment by jhelvy** [comment]
Thanks, I'll add this next chance I get!
