### ISSUE TITLE
Tips & tricks: Modifying the GitHub repo containing my Distill website

### ISSUE THREAD

**Issue by shannonpileggi** [jhelvy/distillery#77]
I guess what not to do is as good as a tip as what to do?

Any who, here is a new post if you think it fits!

Modifying the GitHub repo containing my Distill website: Adventures with giscus (easier) and GitHub Actions (harder)

https://www.pipinghotdata.com/posts/2021-12-13-modifying-the-github-repo-containing-my-distill-website/

**Comment by jhelvy** [comment]
Very nice! Okay, I've got 2 posts to add now (including this one). It's grading time, so maybe early next week I'll pull these in, unless of course you want to make a PR :)

**Comment by shannonpileggi** [comment]
Unfortunately I am having trouble with the PR 😭

- I forgot I had already forked on a prev computer, so tried cloning my fork
- Then I think whatever command I was using was trying to update from master and not main, decided to not go keep googling git
- Then I tried just deleting my original fork on github and then re-doing the fork and clone from your main, and I am still getting this

```
> usethis::create_from_github("https://github.com/jhelvy/distillery", destdir = "C:/Users/pileggis/Documents/gh-personal/")
i Defaulting to 'https' Git protocol
√ Setting `fork = TRUE`
√ Creating 'C:/Users/pileggis/Documents/gh-personal/distillery/'
√ Forking 'jhelvy/distillery'
√ Cloning repo from 'https://github.com/shannonpileggi/distillery.git' into 'C:/Users/pileggis/Documents/gh-personal/distillery'
Error in libgit2::git_clone : 
  cannot checkout to invalid path '_posts/2021-03-24-automagic-tabs-in-distillrmarkdown-files-and-time-series-analysis/automagic-tabs-in-distillrmarkdown-files-and-time-series-analysis_files/figure-html5/`r 2021-03-29 08:12:14 nest_data$sector[[10]]`-1.png'
```

Now I'm not sure anymore if this is a me thing, or if something with that file name is preventing the fork and clone.  Let me know if you have suggestions for something else to try.

**Comment by jhelvy** [comment]
Weird...looks like there's something git doesn't like about that particular file name? I'm not sure what that's about though as others appear to have been able to fork the repo pretty recently without any issues. 

Have you tried just forking it from the website UI? That's actually how I usually fork things as I always seem to run into errors when actually using git. I just do the UI approach and then clone my fork.

**Comment by jhelvy** [comment]
Okay, I went ahead and just added the post (sorry if you were still working on the PR!)

**Comment by shannonpileggi** [comment]
Thanks for completing this! Sorry for the delay, was away from my computer for a couple of days.

Just for completeness, I attempted your suggestion. I deleted my forked repo again, re-forked using the website UI, then try to connect w/ RStudio via 

New Project -> Version control -> git

and I still had the same issue.  Maybe it is a Windows thing??

![image](https://user-images.githubusercontent.com/17747575/146953335-9ecf25e9-79a6-4d84-bd5d-4971391026c6.png)

**Comment by jhelvy** [comment]
I'm actually wondering if it's a RStudio thing in how it connects with git? I use the [github desktop](https://desktop.github.com/) app to manage all git things. Maybe try that to see if it can be cloned? If not, then maybe there's something strange going on with the repo itself.

**Comment by shannonpileggi** [comment]
:(

![image](https://user-images.githubusercontent.com/17747575/146956266-cf1f0547-b26c-4946-9eff-27400eab28b2.png)

**Comment by shannonpileggi** [comment]
Don't know if this is it for sure, but I have had problems with Windows before and super long path names.

**Comment by jhelvy** [comment]
Welp, okay it's not RStudio then. Maybe it is a windows thing. Looking at [those files](https://github.com/jhelvy/distillery/tree/main/_posts/2021-03-24-automagic-tabs-in-distillrmarkdown-files-and-time-series-analysis/automagic-tabs-in-distillrmarkdown-files-and-time-series-analysis_files/figure-html5), they have back-ticks in the file names. Maybe Windows doesn't like that?

**Comment by shannonpileggi** [comment]
🧐 good catch! that could be the culprit, too.

**Comment by jhelvy** [comment]
I just took a closer look at that post and re-built it after updating one of the packages in it to the dev version. The image names changed some (they're dynamically created from a package), but they still have a backtick in the name. I can't be sure that is the culprit, but maybe try again? If it is some strange Windows thing, then I'll have to do something to modify this post so that others can still fork and clone the repo.
