### ISSUE TITLE
Quality of life mods for your distill websites

### ISSUE THREAD

**Issue by jeweljohnsonj** [jhelvy/distillery#79]
Hello everyone, I have written a post on how to add certain features to distill websites/blogs. You can find the post link and its source code link below. There might be some typos that I would have missed, so if you find any please kindly fix them thank you. 

Here is the link to the [post](https://jeweljohnsonj.github.io/jeweljohnson.github.io/posts/2021-12-18-quality-of-life-modifications-for-your-distill-webistes/) and link to the [source code of the post](https://github.com/jeweljohnsonj/jeweljohnson.github.io/blob/main/_posts/2021-12-18-quality-of-life-modifications-for-your-distill-webistes/quality-of-life-modifications-for-your-distill-webistes.Rmd)

**Comment by jhelvy** [comment]
Just added the post!
