### ISSUE TITLE
Bibliometriar

### ISSUE THREAD

**Issue by guillermo-orjuela** [jhelvy/distillery#81]
Hi!
I would like to contribute to the example websites using the distill package.
I created the website named bibliometriar [https://bibliometriar.com/](https://bibliometriar.com/) to explain bibliometric analysis in R in spanish.
The url to the source code is  https://github.com/guillermo-orjuela/bibliometriar

**Comment by jhelvy** [comment]
Welcome! Happy to add your site. Is there a link to the R code that generated the html files? It looks like the source code repo you linked to only have the rendered files.

**Comment by guillermo-orjuela** [comment]
I just uploaded the Rmd files https://github.com/guillermo-orjuela/bibliometriar

**Comment by jhelvy** [comment]
Okay I just added it, should be up soon!

**Comment by guillermo-orjuela** [comment]
Great! Thank you.
By the way, the website name is bibliometriar and my name is Guillermo Orjuela-Ramirez

**Comment by jhelvy** [comment]
Woops, realized I left out the name field in sites.csv. Just fixed it.
